set_property PACKAGE_PIN W5 [get_ports i_clock]							
	set_property IOSTANDARD LVCMOS33 [get_ports i_clock]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports i_clock]

# Switches
set_property PACKAGE_PIN V17 [get_ports {i_reset}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_reset}]
set_property PACKAGE_PIN V16 [get_ports {i_rx_data}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_rx_data}]
set_property PACKAGE_PIN W16 [get_ports {i_reset_clock}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_reset_clock}]
set_property PACKAGE_PIN W15 [get_ports {o_tx_data}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_tx_data}]
set_property PACKAGE_PIN V15 [get_ports {i_rx_parity}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_rx_parity}]
set_property PACKAGE_PIN W14 [get_ports {o_tx_parity}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_tx_parity}]
set_property PACKAGE_PIN V13 [get_ports {o_locked}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_locked}]